package com.edwin.abreusoft.manualbiblicoparacreyentes.Books;

public class BooksText {

    public static final String[][] OT_BOOKS = {
            {"Génesis", "Moisés", "50", "nacimiento o comienzos"},
            {"Éxodo", "Moisés", "40", "salida"},
            {"Levítico", "Moisés", "27", "Libro de la ley"},
            {"Números", "Moisés", "36", "En el desierto"},
            {"Deuteronomio", "Moisés", "34", "Segunda Ley"},
            {"Josué", "Josué", "24", "Jehová Salva"},
            {"Jueces", "Samuel", "21", "Persona que tiene autoridad y potestad para juzgar"},
            {"Rut", "Samuel", "4", "La Compañera fiel"},
            {"1 Samuel", "Samuel, Gad, Natán", "31", "Escuchado por Dios"},
            {"2 Samuel", "Gad, Natán", "24", "Escuchado por Dios"},
            {"1 Reyes", "Jeremías", "22", "El que decide con énfasis en la superioridad intelectual"},
            {"2 Reyes", "Jeremías", "25", "El que decide con énfasis en la superioridad intelectual"},
            {"1 Crónicas", "Esdras", "29", "Los añales de los días"},
            {"2 Crónicas", "Esdras", "36", "Los añales de los días"},
            {"Esdras", "Esdras", "10", "El que Dios ayuda"},
            {"Nehemías", "Nehemías", "13", "Jehová ha consolado"},
            {"Ester", "Mardoqueo", "10", "Estrella, astro"},
            {"Job", "Moisés", "42", "El perseguido o Aborrecido"},
            {"Salmos", "David y otros", "150", "Alabanzas al Rey"},
            {"Proverbios", "Salomón, Agur, Lemuel", "31", "Escritos Sapiensales"},
            {"Eclesiastés", "Salomón", "12", "Asambleísta o Congregista"},
            {"El Cantar de los Cantares", "Salomón", "8", "Canto de amor que representa la belleza de una relación humana como símbolo de amor divino"},
            {"Isaías", "Isaías", "66", "La principal profecía de condena y consolación mesiánica"},
            {"Jeremías", "Jeremías", "52", "Mensaje de juicio contra la moral de Judá y el deterioramiento espiritual"},
            {"Lamentaciones", "Jeremías", "5", "Cinco poemas de lamento por la caída de Jerusalén"},
            {"Ezequiel", "Ezequiel", "48", "Profecía del juicio durante el cautiverio babilónico"},
            {"Daniel", "Daniel", "12", "Libro de profecía sobre los postreros tiempos"},
            {"Oseas", "Oseas", "14", "Mensaje de condenación a Israel seguido por el perdón de Dios"},
            {"Joel", "Joel", "3", "Predicción de la invasión extranjera como juicio de Dios"},
            {"Amós", "Amós", "9", "Edicto de juicio contra las naciones, sobre todo a Israel"},
            {"Abdías", "Abdías", "1", "Libro que profetiza la destrucción total de Edom"},
            {"Jonás", "Jonás", "4", "Relato de un profeta desobediente que llevó a Nínive al arrepentimiento"},
            {"Miqueas", "Miqueas", "7", "Predicción de juicio y promesa de restauración mesiánica"},
            {"Nahúm", "Nahúm", "3", "Profecía sobre la destrucción de Nínive"},
            {"Habacuc", "Habacuc", "3", "Un profeta que discutió con Dios y alabó su inminente juicio contra Judá"},
            {"Sofonías", "Sofonías", "3", "Predicción de juicio destructivo seguida de tremenda bendición"},
            {"Ageo", "Ageo", "2", "Llamado a reedificar el templo después que regresan de Babilonia"},
            {"Zacarías", "Zacarías", "14", "Profecía mesiánica que llama a terminar la construcción del templo"},
            {"Malaquías", "Malaquías", "4", "Profecía de destrucción seguida de la bendición mesiánica"}
    };

    public static final String[][] NT_BOOKS = {
            {"Mateo", "Mateo", "28", ""},
            {"Marcos", "Marcos", "16", ""},
            {"Lucas", "Lucas", "24", ""},
            {"Juan", "Juan", "21", ""},
            {"Hechos", "Lucas", "28", ""},
            {"Romanos", "Pablo", "16", ""},
            {"1 Corintios", "Pablo", "16", ""},
            {"2 Corintios", "Pablo", "13", ""},
            {"Galatas", "Pablo", "6", ""},
            {"Efesios", "Pablo", "6", ""},
            {"Filipenses", "Pablo", "4", ""},
            {"Colosenses", "Pablo", "4", ""},
            {"1 Tesalonicenses", "Pablo", "5", ""},
            {"2 Tesalonicenses", "Pablo", "3", ""},
            {"1 Timoteo", "Pablo", "6", ""},
            {"2 Timoteo", "Pablo", "4", ""},
            {"Filemón", "Pablo", "3", ""},
            {"Hebreos", "desconocido", "13", ""},
            {"Santiago", "Santiago", "5", ""},
            {"1 Pedro", "Pedro", "5", ""},
            {"2 Pedro", "Pedro", "3", ""},
            {"1 Juan", "Juan", "5", ""},
            {"2 Juan", "Juan", "1", ""},
            {"3 Juan", "Juan", "1", ""},
            {"Judas", "Judas", "1", ""},
            {"Apocalipsis", "Juan", "22", ""}
    };

}
