package com.edwin.abreusoft.manualbiblicoparacreyentes.Texts;

public class Verses {

    public static final  String[][] OT_MOSES = {
            {"Génesis", "12:3", "Bendeciré a los que te bendijeren, y a los que te maldijeren maldeciré; y serán benditas en ti todas las familias de la tierra."},
            {"Génesis", "28:15", "He aquí, yo estoy contigo, y te guardaré por dondequiera que fueres, y volveré a traerte a esta tierra; porque no te dejaré hasta que haya hecho lo que te he dicho."},
            {"Génesis", "39:2", "Mas Jehová estaba con José, y fue varón próspero; y estaba en la casa de su amo el egipcio."},
            {"Génesis", "39:21", "Pero Jehová estaba con José y le extendió su misericordia, y le dio gracia en los ojos del jefe de la cárcel."},
            {"Éxodo", "14:14", "Jehová peleará por vosotros, y vosotros estaréis tranquilos."},
            {"Éxodo", "15:2", "Jehová es mi fortaleza y mi cántico, y ha sido mi salvación. Este es mi Dios, y lo alabaré; Dios de mi padre, y lo enalteceré."},
            {"Éxodo", "19:5", "Ahora, pues, si diereis oído a mi voz, y guardareis mi pacto, vosotros seréis mi especial tesoro sobre todos los pueblos; porque mía es toda la tierra."},
            {"Éxodo", "20:6", "Y hago misericordia a millares, a los que me aman y guardan mis mandamientos."},
            {"Éxodo", "23:25", "Mas a Jehová vuestro Dios serviréis, y él bendecirá tu pan y tus aguas; y yo quitaré toda enfermedad de en medio de ti."},
            {"Éxodo", "33:14", "Y él dijo: Mi presencia irá contigo, y te daré descanso."},
            {"Levítico", "3:17", "Estatuto perpetuo será por vuestras edades, dondequiera que habitéis, que ninguna grosura ni ninguna sangre comeréis."},
            {"Levítico", "8:6", "Entonces Moisés hizo acercarse a Aarón y a sus hijos, y los lavó con agua."},
            {"Levítico", "18:5", "Por tanto, guardaréis mis estatutos y mis ordenanzas, los cuales haciendo el hombre, vivirá en ellos. Yo Jehová."},
            {"Levítico", "26:12", "y andaré entre vosotros, y yo seré vuestro Dios, y vosotros seréis mi pueblo."},
            {"Números", "3:6", "Haz que se acerque la tribu de Leví, y hazla estar delante del sacerdote Aarón, para que le sirvan,"},
            {"Números", "6:24", "Jehová te bendiga, y te guarde;"},
            {"Números", "11:23", "Entonces Jehová respondió a Moisés: ¿Acaso se ha acortado la mano de Jehová? Ahora verás si se cumple mi palabra, o no."},
            {"Deuteronomio", "4:7", "Porque ¿qué nación grande hay que tenga dioses tan cercanos a ellos como lo está Jehová nuestro Dios en todo cuanto le pedimos?"},
            {"Deuteronomio", "4:40", "Y guarda sus estatutos y sus mandamientos, los cuales yo te mando hoy, para que te vaya bien a ti y a tus hijos después de ti, y prolongues tus días sobre la tierra que Jehová tu Dios te da para siempre."},
            {"Deuteronomio", "7:15", "Y quitará Jehová de ti toda enfermedad; y todas las malas plagas de Egipto, que tú conoces, no las pondrá sobre ti, antes las pondrá sobre todos los que te aborrecieren."},
            {"Deuteronomio", "10:12", "Ahora, pues, Israel, ¿qué pide Jehová tu Dios de ti, sino que temas a Jehová tu Dios, que andes en todos sus caminos, y que lo ames, y sirvas a Jehová tu Dios con todo tu corazón y con toda tu alma;"},
            {"Deuteronomio", "29:29", "Las cosas secretas pertenecen a Jehová nuestro Dios; mas las reveladas son para nosotros y para nuestros hijos para siempre, para que cumplamos todas las palabras de esta ley."},
            {"Deuteronomio", "31:8", "Y Jehová va delante de ti; él estará contigo, no te dejará, ni te desamparará; no temas ni te intimides."}
    };

    public static final  String[][] OT_HISTORICAL = {
            {"Josué", "1:8", "Nunca se apartará de tu boca este libro de la ley, sino que de día y de noche meditarás en él, para que guardes y hagas conforme a todo lo que en él está escrito; porque entonces harás prosperar tu camino, y todo te saldrá bien."},
            {"Josué", "1:9", "Mira que te mando que te esfuerces y seas valiente; no temas ni desmayes, porque Jehová tu Dios estará contigo en dondequiera que vayas."},
            {"Josué", "3:7", "Entonces Jehová dijo a Josué: Desde este día comenzaré a engrandecerte delante de los ojos de todo Israel, para que entiendan que como estuve con Moisés, así estaré contigo."},
            {"Josué", "24:16", "Entonces el pueblo respondió y dijo: Nunca tal acontezca, que dejemos a Jehová para servir a otros dioses;"},
            {"Jueces", "2:1", "El ángel de Jehová subió de Gilgal a Boquim, y dijo: Yo os saqué de Egipto, y os introduje en la tierra de la cual había jurado a vuestros padres, diciendo: No invalidaré jamás mi pacto con vosotros,"},
            {"Jueces", "6:16", "Jehová le dijo: Ciertamente yo estaré contigo, y derrotarás a los madianitas como a un solo hombre."},
            {"1 Samuel", "2:8", "El levanta del polvo al pobre, y del muladar exalta al menesteroso, para hacerle sentarse con príncipes y heredar un sitio de honor. Porque de Jehová son las columnas de la tierra, y él afirmó sobre ellas el mundo."},
            {"1 Samuel", "2:9", "El guarda los pies de sus santos, mas los impíos perecen en tinieblas; porque nadie será fuerte por su propia fuerza."},
            {"1 Samuel", "2:30", "Por tanto, Jehová el Dios de Israel dice: Yo había dicho que tu casa y la casa de tu padre andarían delante de mí perpetuamente; mas ahora ha dicho Jehová: Nunca yo tal haga, porque yo honraré a los que me honran, y los que me desprecian serán tenidos en poco."},
            {"1 Samuel", "12:22", "Pues Jehová no desamparará a su pueblo, por su grande nombre; porque Jehová ha querido haceros pueblo suyo."},
            {"1 Samuel", "15:22", "Y Samuel dijo: ¿Se complace Jehová tanto en los holocaustos y víctimas, como en que se obedezca a las palabras de Jehová? Ciertamente el obedecer es mejor que los sacrificios, y el prestar atención que la grosura de los carneros."},
            {"1 Samuel", "16:7", "Y Jehová respondió a Samuel: No mires a su parecer, ni a lo grande de su estatura, porque yo lo desecho; porque Jehová no mira lo que mira el hombre; pues el hombre mira lo que está delante de sus ojos, pero Jehová mira el corazón."},
            {"2 Samuel", "7:14", "Yo le seré a él padre, y él me será a mí hijo. Y si él hiciere mal, yo le castigaré con vara de hombres, y con azotes de hijos de hombres;"},
            {"2 Samuel", "7:28", "Ahora pues, Jehová Dios, tú eres Dios, y tus palabras son verdad, y tú has prometido este bien a tu siervo."},
            {"2 Samuel", "22:4", "Invocaré a Jehová, quien es digno de ser alabado, Y seré salvo de mis enemigos."},
            {"2 Samuel", "22:21", "Jehová me ha premiado conforme a mi justicia; Conforme a la limpieza de mis manos me ha recompensado."},
            {"1 Reyes", "1:29", "Y el rey juró diciendo: Vive Jehová, que ha redimido mi alma de toda angustia,"},
            {"1 Reyes", "2:3", "Guarda los preceptos de Jehová tu Dios, andando en sus caminos, y observando sus estatutos y mandamientos, sus decretos y sus testimonios, de la manera que está escrito en la ley de Moisés, para que prosperes en todo lo que hagas y en todo aquello que emprendas."},
            {"1 Reyes", "8:45", "tú oirás en los cielos su oración y su súplica, y les harás justicia."},
            {"1 Reyes", "8:56", "Bendito sea Jehová, que ha dado paz a su pueblo Israel, conforme a todo lo que él había dicho; ninguna palabra de todas sus promesas que expresó por Moisés su siervo, ha faltado."},
            {"2 Reyes", "5:10", "Entonces Eliseo le envió un mensajero, diciendo: Ve y lávate siete veces en el Jordán, y tu carne se te restaurará, y serás limpio."},
            {"2 Reyes", "10:12", " Luego se levantó de allí para ir a Samaria; y en el camino llegó a una casa de esquileo de pastores."},
            {"2 Reyes", "19:34", "Porque yo ampararé esta ciudad para salvarla, por amor a mí mismo, y por amor a David mi siervo."},
            {"1 Crónicas", "16:8", " Alabad a Jehová, invocad su nombre, Dad a conocer en los pueblos sus obras."},
            {"1 Crónicas", "16:10", "Gloriaos en su santo nombre; Alégrese el corazón de los que buscan a Jehová."},
            {"1 Crónicas", "16:11", "Buscad a Jehová y su poder; Buscad su rostro continuamente."},
            {"1 Crónicas", "22:13", "Entonces serás prosperado, si cuidares de poner por obra los estatutos y decretos que Jehová mandó a Moisés para Israel. Esfuérzate, pues, y cobra ánimo; no temas, ni desmayes."},
            {"1 Crónicas", "29:12", "Las riquezas y la gloria proceden de ti, y tú dominas sobre todo; en tu mano está la fuerza y el poder, y en tu mano el hacer grande y el dar poder a todos."},
            {"1 Crónicas", "13:14", "Y el arca de Dios estuvo con la familia de Obed-edom, en su casa, tres meses; y bendijo Jehová la casa de Obed-edom, y todo lo que tenía."},
            {"2 Crónicas", "6:15", "que has guardado a tu siervo David mi padre lo que le prometiste; tú lo dijiste con tu boca, y con tu mano lo has cumplido, como se ve en este día."},
            {"2 Crónicas", "6:19", "Mas tú mirarás a la oración de tu siervo, y a su ruego, oh Jehová Dios mío, para oír el clamor y la oración con que tu siervo ora delante de ti."},
            {"2 Crónicas", "7:14", "si se humillare mi pueblo, sobre el cual mi nombre es invocado, y oraren, y buscaren mi rostro, y se convirtieren de sus malos caminos; entonces yo oiré desde los cielos, y perdonaré sus pecados, y sanaré su tierra."},
            {"2 Crónicas", "15:4", "pero cuando en su tribulación se convirtieron a Jehová Dios de Israel, y le buscaron, él fue hallado de ellos."},
            {"2 Crónicas", "15:7", "Pero esforzaos vosotros, y no desfallezcan vuestras manos, pues hay recompensa para vuestra obra."},
            {"2 Crónicas", "19:9", "Y les mandó diciendo: Procederéis asimismo con temor de Jehová, con verdad, y con corazón íntegro."},
            {"2 Crónicas", "31:21", "En todo cuanto emprendió en el servicio de la casa de Dios, de acuerdo con la ley y los mandamientos, buscó a su Dios, lo hizo de todo corazón, y fue prosperado."},
            {"Esdras", "3:11", "Y cantaban, alabando y dando gracias a Jehová, y diciendo: Porque él es bueno, porque para siempre es su misericordia sobre Israel. Y todo el pueblo aclamaba con gran júbilo, alabando a Jehová porque se echaban los cimientos de la casa de Jehová."},
            {"Esdras", "7:6", "este Esdras subió de Babilonia. Era escriba diligente en la ley de Moisés, que Jehová Dios de Israel había dado; y le concedió el rey todo lo que pidió, porque la mano de Jehová su Dios estaba sobre Esdras."},
            {"Esdras", "7:10", "Porque Esdras había preparado su corazón para inquirir la ley de Jehová y para cumplirla, y para enseñar en Israel sus estatutos y decretos."},
            {"Esdras", "8:23", "Ayunamos, pues, y pedimos a nuestro Dios sobre esto, y él nos fue propicio."},
            {"Nehemías", "1:5", "Y dije: Te ruego, oh Jehová, Dios de los cielos, fuerte, grande y temible, que guarda el pacto y la misericordia a los que le aman y guardan sus mandamientos;"},
            {"Nehemías", "1:6", "esté ahora atento tu oído y abiertos tus ojos para oír la oración de tu siervo, que hago ahora delante de ti día y noche, por los hijos de Israel tus siervos; y confieso los pecados de los hijos de Israel que hemos cometido contra ti; sí, yo y la casa de mi padre hemos pecado."},
            {"Nehemías", "1:9", "pero si os volviereis a mí, y guardareis mis mandamientos, y los pusiereis por obra, aunque vuestra dispersión fuere hasta el extremo de los cielos, de allí os recogeré, y os traeré al lugar que escogí para hacer habitar allí mi nombre."},
            {"Nehemías", "5:19", "Acuérdate de mí para bien, Dios mío, y de todo lo que hice por este pueblo."},
            {"Nehemías", "8:6", "Bendijo entonces Esdras a Jehová, Dios grande. Y todo el pueblo respondió: !!Amén! !!Amén! alzando sus manos; y se humillaron y adoraron a Jehová inclinados a tierra."},
            {"Nehemías", "9:33", "Pero tú eres justo en todo lo que ha venido sobre nosotros; porque rectamente has hecho, mas nosotros hemos hecho lo malo."},
    };

    public static final  String[][] OT_POETRY = {
            {"Job", "5:8", "Ciertamente yo buscaría a Dios, Y encomendaría a él mi causa;"},
            {"Job", "5:17", "He aquí, bienaventurado es el hombre a quien Dios castiga; Por tanto, no menosprecies la corrección del Todopoderoso."},
            {"Job", "23:4", "Mis labios no hablarán iniquidad, Ni mi lengua pronunciará engaño."},
            {"Job", "40:2", "¿Es sabiduría contender con el Omnipotente? El que disputa con Dios, responda a esto."},
            {"Job", "42:2", "Yo conozco que todo lo puedes, Y que no hay pensamiento que se esconda de ti."},
            {"Job", "42:4", "Oye, te ruego, y hablaré; Te preguntaré, y tú me enseñarás."},
            {"Job", "8:6", "Si fueres limpio y recto, Ciertamente luego se despertará por ti, Y hará próspera la morada de tu justicia."},
            {"Job", "11:18", "Tendrás confianza, porque hay esperanza; mirarás alrededor, y dormirás seguro."},
            {"Job", "22:21", "Vuelve ahora en amistad con él, y tendrás paz; y por ello te vendrá bien."},
            {"Job", "22:27", "Orarás a él, y él te oirá; y tú pagarás tus votos."},
            {"Job", "28:28", "Y dijo al hombre: He aquí que el temor del Señor es la sabiduría, y el apartarse del mal, la inteligencia."},
            {"Job", "36:11", "Si oyeren, y le sirvieren, acabarán sus días en bienestar, y sus años en dicha."},
            {"Salmos", "1:6", "Porque Jehová conoce el camino de los justos; Mas la senda de los malos perecerá."},
            {"Salmos", "3:3", "Mas tú, Jehová, eres escudo alrededor de mí; Mi gloria, y el que levanta mi cabeza. "},
            {"Salmos", "3:5", "Yo me acosté y dormí, Y desperté, porque Jehová me sustentaba."},
            {"Salmos", "4:3", "Sabed, pues, que Jehová ha escogido al piadoso para sí; Jehová oirá cuando yo a él clamare."},
            {"Salmos", "4:8", "En paz me acostaré, y asimismo dormiré; Porque solo tú, Jehová, me haces vivir confiado."},
            {"Salmos", "11:4", "Jehová está en su santo templo; Jehová tiene en el cielo su trono; Sus ojos ven, sus párpados examinan a los hijos de los hombres. "},
            {"Salmos", "11:7", "Porque Jehová es justo, y ama la justicia; El hombre recto mirará su rostro."},
            {"Salmos", "12:6", "Las palabras de Jehová son palabras limpias, Como plata refinada en horno de tierra, Purificada siete veces."},
            {"Salmos", "19:7", "La ley de Jehová es perfecta, que convierte el alma; El testimonio de Jehová es fiel, que hace sabio al sencillo."},
            {"Salmos", "19:14", "Sean gratos los dichos de mi boca y la meditación de mi corazón delante de ti, Oh Jehová, roca mía, y redentor mío."},
            {"Salmos", "24:8", "¿Quién es este Rey de gloria? Jehová el fuerte y valiente, Jehová el poderoso en batalla."},
            {"Salmos", "27:1", "Jehová es mi luz y mi salvación; ¿de quién temeré? Jehová es la fortaleza de mi vida; ¿de quién he de atemorizarme?"},
            {"Salmos", "40:17", "Aunque afligido yo y necesitado, Jehová pensará en mí. Mi ayuda y mi libertador eres tú; Dios mío, no te tardes."},
            {"Salmos", "42:2", "Mi alma tiene sed de Dios, del Dios vivo; ¿Cuándo vendré, y me presentaré delante de Dios?"},
            {"Salmos", "87:10", "Porque mejor es un día en tus atrios que mil fuera de ellos. Escogería antes estar a la puerta de la casa de mi Dios, Que habitar en las moradas de maldad."},
            {"Salmos", "119:37", "Aparta mis ojos, que no vean la vanidad; Avívame en tu camino."},
            {"Salmos", "127:3", "He aquí, herencia de Jehová son los hijos; Cosa de estima el fruto del vientre"},
            {"Proverbios", "1:7", "El principio de la sabiduría es el temor de Jehová; los insensatos desprecian la sabiduría y la enseñanza."},
            {"Proverbios", "2:7", "El provee de sana sabiduría a los rectos; es escudo a los que caminan rectamente."},
            {"Proverbios", "3:5", "Fíate de Jehová de todo tu corazón, y no te apoyes en tu propia prudencia."},
            {"Proverbios", "3:8", "Honra a Jehová con tus bienes, y con las primicias de todos tus frutos;"},
            {"Proverbios", "8:17", "Yo amo a los que me aman, y me hallan los que temprano me buscan."},
            {"Proverbios", "8:35", "Porque el que me halle, hallará la vida, y alcanzará el favor de Jehová."},
            {"Proverbios", "10:12", "El odio despierta rencillas; pero el amor cubrirá todas las faltas."},
            {"Proverbios", "10:22", "La bendición de Jehová es la que enriquece, y no añade tristeza con ella."},
            {"Proverbios", "11:25", "El alma generosa será prosperada; y el que saciare, él también será saciado."},
            {"Proverbios", "11:30", "El fruto del justo es árbol de vida; y el que gana almas es sabio."},
            {"Proverbios", "12:15", "El camino del necio es derecho en su opinión; mas el que obedece al consejo es sabio."},
            {"Proverbios", "12:24", "La mano de los diligentes señoreará; mas la negligencia será tributaria."},
            {"Proverbios", "13:4", "El alma del perezoso desea, y nada alcanza; mas el alma de los diligentes será prosperada."},
            {"Proverbios", "13:24", "El que detiene el castigo, a su hijo aborrece; mas el que lo ama, desde temprano lo corrige."},
            {"Proverbios", "14:1", "La mujer sabia edifica su casa; mas la necia con sus manos la derriba."},
            {"Proverbios", "14:32", "Por su maldad será lanzado el impío; mas el justo en su muerte tiene esperanza."},
            {"Proverbios", "15:1", "La blanda respuesta quita la ira; mas la palabra áspera hace subir el furor."},
            {"Proverbios", "15:16", "Mejor es lo poco con el temor de Jehová, que el gran tesoro donde hay turbación."},
            {"Proverbios", "15:29", "Jehová está lejos de los impíos; pero él oye la oración de los justos."},
            {"Proverbios", "16:3", "Encomienda a Jehová tus obras, y tus pensamientos serán afirmados."},
            {"Proverbios", "16:20", "El entendido en la palabra hallará el bien, y el que confía en Jehová es bienaventurado."},
            {"Proverbios", "17:22", "El corazón alegre constituye buen remedio; mas el espíritu triste seca los huesos."},
            {"Proverbios", "19:17", "A Jehová presta el que da al pobre, y el bien que ha hecho, se lo volverá a pagar."},
            {"Proverbios", "20:21", "Los bienes que se adquieren de prisa al principio, no serán al final bendecidos."},
            {"Proverbios", "21:5", "Los pensamientos del diligente ciertamente tienden a la abundancia; mas todo el que se apresura alocadamente, de cierto va a la pobreza."},
            {"Proverbios", "21:21", "El que sigue la justicia y la misericordia hallará la vida, la justicia y la honra."},
            {"Proverbios", "22:9", "El ojo misericordioso será bendito, porque dio de su pan al indigente."},
            {"Proverbios", "23:13", "No rehúses corregir al muchacho; porque si lo castigas con vara, no morirá."},
            {"Proverbios", "23:22", "Oye a tu padre, a aquel que te engendró; y cuando tu madre envejeciere, no la menosprecies."},
            {"Proverbios", "28:13", "El que encubre sus pecados no prosperará; mas el que los confiesa y se aparta alcanzará misericordia."},
            {"Proverbios", "29:17", "Corrige a tu hijo, y te dará descanso, y dará alegría a tu alma."},
            {"Proverbios", "30:6", "No añadas a sus palabras, para que no te reprenda, y seas hallado mentiroso."},
            {"Eclesiastés", "1:18", "Porque en la mucha sabiduría hay mucha molestia; y quien añade ciencia, añade dolor."},
            {"Eclesiastés", "3:1", "Todo tiene su tiempo, y todo lo que se quiere debajo del cielo tiene su hora."},
            {"Eclesiastés", "3:13", "Y también que es don de Dios que todo hombre coma y beba, y goce el bien de toda su labor."},
            {"Eclesiastés", "4:9", "Mejores son dos que uno; porque tienen mejor paga de su trabajo."},
            {"Eclesiastés", "5:1", "Cuando fueres a la casa de Dios, guarda tu pie; y acércate más para oír que para ofrecer el sacrificio de los necios; porque no saben que hacen mal."},
            {"Eclesiastés", "5:4", "Cuando a Dios haces promesa, no tardes en cumplirla; porque él no se complace en los insensatos. Cumple lo que prometes."},
            {"Eclesiastés", "5:12", "Dulce es el sueño del trabajador, coma mucho, coma poco; pero al rico no le deja dormir la abundancia."},
            {"Eclesiastés", "7:9", "No te apresures en tu espíritu a enojarte; porque el enojo reposa en el seno de los necios."},
            {"Eclesiastés", "7:14", "En el día del bien goza del bien; y en el día de la adversidad considera. Dios hizo tanto lo uno como lo otro, a fin de que el hombre nada halle después de él."},
            {"Eclesiastés", "8:3", "No te apresures a irte de su presencia, ni en cosa mala persistas; porque él hará todo lo que quiere."},
            {"Eclesiastés", "8:12", "Aunque el pecador haga mal cien veces, y prolongue sus días, con todo yo también sé que les irá bien a los que a Dios temen, los que temen ante su presencia."},
            {"Eclesiastés", "12:14", "Porque Dios traerá toda obra a juicio, juntamente con toda cosa encubierta, sea buena o sea mala."}
    };

    public static final  String[][] OT_MAJ_PROPHETS = {
            {"Isaías", "1:17", "aprended a hacer el bien; buscad el juicio, restituid al agraviado, haced justicia al huérfano, amparad a la viuda."},
            {"Isaías", "3:10", "Decid al justo que le irá bien, porque comerá de los frutos de sus manos."},
            {"Isaías", "8:13", "A Jehová de los ejércitos, a él santificad; sea él vuestro temor, y él sea vuestro miedo."},
            {"Isaías", "12:5", "Cantad salmos a Jehová, porque ha hecho cosas magníficas; sea sabido esto por toda la tierra."},
            {"Isaías", "26:3", "Tú guardarás en completa paz a aquel cuyo pensamiento en ti persevera; porque en ti ha confiado."},
            {"Isaías", "50:10", "¿Quién hay entre vosotros que teme a Jehová, y oye la voz de su siervo? El que anda en tinieblas y carece de luz, confíe en el nombre de Jehová, y apóyese en su Dios."},
            {"Jeremías", "9:24", "Mas alábese en esto el que se hubiere de alabar: en entenderme y conocerme, que yo soy Jehová, que hago misericordia, juicio y justicia en la tierra; porque estas cosas quiero, dice Jehová."},
            {"Jeremías", "10:2", "Así dijo Jehová: No aprendáis el camino de las naciones, ni de las señales del cielo tengáis temor, aunque las naciones las teman."},
            {"Jeremías", "15:19", "Por tanto, así dijo Jehová: Si te convirtieres, yo te restauraré, y delante de mí estarás; y si entresacares lo precioso de lo vil, serás como mi boca. Conviértanse ellos a ti, y tú no te conviertas a ellos."},
            {"Jeremías", "17:7", "Bendito el varón que confía en Jehová, y cuya confianza es Jehová."},
            {"Jeremías", "23:28", "El profeta que tuviere un sueño, cuente el sueño; y aquel a quien fuere mi palabra, cuente mi palabra verdadera. ¿Qué tiene que ver la paja con el trigo? dice Jehová."},
            {"Jeremías", "50:8", " Huid de en medio de Babilonia, y salid de la tierra de los caldeos, y sed como los machos cabríos que van delante del rebaño."},
            {"Lamentaciones", "3:22", "Por la misericordia de Jehová no hemos sido consumidos, porque nunca decayeron sus misericordias."},
            {"Lamentaciones", "3:27", "Bueno le es al hombre llevar el yugo desde su juventud."},
            {"Lamentaciones", "3:40", "Escudriñemos nuestros caminos, y busquemos, y volvámonos a Jehová;"},
            {"Lamentaciones", "5:21", "Vuélvenos, oh Jehová, a ti, y nos volveremos; Renueva nuestros días como al principio."},
            {"Ezequiel", "6:8", "Mas dejaré un resto, de modo que tengáis entre las naciones algunos que escapen de la espada, cuando seáis esparcidos por las tierras."},
            {"Ezequiel", "12:28", "Diles, por tanto: Así ha dicho Jehová el Señor: No se tardará más ninguna de mis palabras, sino que la palabra que yo hable se cumplirá, dice Jehová el Señor."},
            {"Ezequiel", "17:23", "En el monte alto de Israel lo plantaré, y alzará ramas, y dará fruto, y se hará magnífico cedro; y habitarán debajo de él todas las aves de toda especie; a la sombra de sus ramas habitarán"},
            {"Ezequiel", "18:32", "Porque no quiero la muerte del que muere, dice Jehová el Señor; convertíos, pues, y viviréis."},
            {"Ezequiel", "36:27", "Y pondré dentro de vosotros mi Espíritu, y haré que andéis en mis estatutos, y guardéis mis preceptos, y los pongáis por obra."},
            {"Ezequiel", "37:14", "Y pondré mi Espíritu en vosotros, y viviréis, y os haré reposar sobre vuestra tierra; y sabréis que yo Jehová hablé, y lo hice, dice Jehová."},
            {"Daniel", "2:20", "Y Daniel habló y dijo: Sea bendito el nombre de Dios de siglos en siglos, porque suyos son el poder y la sabiduría. "},
            {"Daniel", "3:17", "He aquí nuestro Dios a quien servimos puede librarnos del horno de fuego ardiendo; y de tu mano, oh rey, nos librará."},
            {"Daniel", "4:2", "Conviene que yo declare las señales y milagros que el Dios Altísimo ha hecho conmigo."},
            {"Daniel", "9:9", "De Jehová nuestro Dios es el tener misericordia y el perdonar, aunque contra él nos hemos rebelado,"}
    };

    public static final  String[][] OT_MIN_PROPHETS = {
            {"Oseas", "2:19", "Y te desposaré conmigo para siempre; te desposaré conmigo en justicia, juicio, benignidad y misericordia."},
            {"Oseas", "2:20", "Y te desposaré conmigo en fidelidad, y conocerás a Jehová."},
            {"Oseas", "5:15", "Andaré y volveré a mi lugar, hasta que reconozcan su pecado y busquen mi rostro. En su angustia me buscarán."},
            {"Oseas", "10:12", "Sembrad para vosotros en justicia, segad para vosotros en misericordia; haced para vosotros barbecho; porque es el tiempo de buscar a Jehová, hasta que venga y os enseñe justicia."},
            {"Joel", "2:12", "Por eso pues, ahora, dice Jehová, convertíos a mí con todo vuestro corazón, con ayuno y lloro y lamento."},
            {"Joel", "2:13", "Rasgad vuestro corazón, y no vuestros vestidos, y convertíos a Jehová vuestro Dios; porque misericordioso es y clemente, tardo para la ira y grande en misericordia, y que se duele del castigo."},
            {"Joel", "2:21", "Tierra, no temas; alégrate y gózate, porque Jehová hará grandes cosas."},
            {"Joel", "2:32", "Y todo aquel que invocare el nombre de Jehová será salvo; porque en el monte de Sion y en Jerusalén habrá salvación, como ha dicho Jehová, y entre el remanente al cual él habrá llamado."},
            {"Amós", "3:3", "¿Andarán dos juntos, si no estuvieren de acuerdo?"},
            {"Amós", "5:14", "Buscad lo bueno, y no lo malo, para que viváis; porque así Jehová Dios de los ejércitos estará con vosotros, como decís."},
            {"Amós", "5:15", "Aborreced el mal, y amad el bien, y estableced la justicia en juicio; quizá Jehová Dios de los ejércitos tendrá piedad del remanente de José."},
            {"Abdías", "1:17", "Mas en el monte de Sion habrá un remanente que se salve; y será santo, y la casa de Jacob recuperará sus posesiones."},
            {"Abdías", "1:21", "Y subirán salvadores al monte de Sion para juzgar al monte de Esaú; y el reino será de Jehová."},
            {"Jonás", "2:2", "y dijo: Invoqué en mi angustia a Jehová, y él me oyó; Desde el seno del Seol clamé, Y mi voz oíste."},
            {"Jonás", "2:7", "Cuando mi alma desfallecía en mí, me acordé de Jehová, Y mi oración llegó hasta ti en tu santo templo."},
            {"Jonás", "2:9", "Mas yo con voz de alabanza te ofreceré sacrificios; Pagaré lo que prometí. La salvación es de Jehová."},
            {"Jonás", "3:10", "Y vio Dios lo que hicieron, que se convirtieron de su mal camino; y se arrepintió del mal que había dicho que les haría, y no lo hizo."},
            {"Miqueas", "4:5", "Aunque todos los pueblos anden cada uno en el nombre de su dios, nosotros con todo andaremos en el nombre de Jehová nuestro Dios eternamente y para siempre."},
            {"Miqueas", "6:8", "Oh hombre, él te ha declarado lo que es bueno, y qué pide Jehová de ti: solamente hacer justicia, y amar misericordia, y humillarte ante tu Dios."},
            {"Miqueas", "7:18", "¿Qué Dios como tú, que perdona la maldad, y olvida el pecado del remanente de su heredad? No retuvo para siempre su enojo, porque se deleita en misericordia."},
            {"Miqueas", "7:19", "El volverá a tener misericordia de nosotros; sepultará nuestras iniquidades, y echará en lo profundo del mar todos nuestros pecados."},
            {"Nahum", "1:3", " Jehová es tardo para la ira y grande en poder, y no tendrá por inocente al culpable. Jehová marcha en la tempestad y el torbellino, y las nubes son el polvo de sus pies."},
            {"Nahum", "1:7", "Jehová es bueno, fortaleza en el día de la angustia; y conoce a los que en él confían."},
            {"Nahum", "2:2", "Porque Jehová restaurará la gloria de Jacob como la gloria de Israel; porque saqueadores los saquearon, y estropearon sus mugrones."},
            {"Habacuc", "2:3", "Aunque la visión tardará aún por un tiempo, mas se apresura hacia el fin, y no mentirá; aunque tardare, espéralo, porque sin duda vendrá, no tardará."},
            {"Habacuc", "2:4", "He aquí que aquel cuya alma no es recta, se enorgullece; mas el justo por su fe vivirá."},
            {"Habacuc", "3:18", "Con todo, yo me alegraré en Jehová, Y me gozaré en el Dios de mi salvación."},
            {"Habacuc", "3:19", "Jehová el Señor es mi fortaleza, El cual hace mis pies como de ciervas, Y en mis alturas me hace andar..."},
            {"Sofonías", "2:3", "Buscad a Jehová todos los humildes de la tierra, los que pusisteis por obra su juicio; buscad justicia, buscad mansedumbre; quizá seréis guardados en el día del enojo de Jehová."},
            {"Sofonías", "3:9", "En aquel tiempo devolveré yo a los pueblos pureza de labios, para que todos invoquen el nombre de Jehová, para que le sirvan de común consentimiento."},
            {"Sofonías", "3:13", "El remanente de Israel no hará injusticia ni dirá mentira, ni en boca de ellos se hallará lengua engañosa; porque ellos serán apacentados, y dormirán, y no habrá quien los atemorice."},
            {"Sofonías", "3:20", "n aquel tiempo yo os traeré, en aquel tiempo os reuniré yo; pues os pondré para renombre y para alabanza entre todos los pueblos de la tierra, cuando levante vuestro cautiverio delante de vuestros ojos, dice Jehová."},
            {"Hageo", "1:7", "Así ha dicho Jehová de los ejércitos: Meditad sobre vuestros caminos."},
            {"Hageo", "1:8", " Subid al monte, y traed madera, y reedificad la casa; y pondré en ella mi voluntad, y seré glorificado, ha dicho Jehová."},
            {"Hageo", "2:5", "Según el pacto que hice con vosotros cuando salisteis de Egipto, así mi Espíritu estará en medio de vosotros, no temáis."},
            {"Zacarías", "1:3", "Diles, pues: Así ha dicho Jehová de los ejércitos: Volveos a mí, dice Jehová de los ejércitos, y yo me volveré a vosotros, ha dicho Jehová de los ejércitos."},
            {"Zacarías", "8:7", "Así ha dicho Jehová de los ejércitos: He aquí, yo salvo a mi pueblo de la tierra del oriente, y de la tierra donde se pone el sol;"},
            {"Zacarías", "8:8", "y los traeré, y habitarán en medio de Jerusalén; y me serán por pueblo, y yo seré a ellos por Dios en verdad y en justicia."},
            {"Zacarías", "13:9", "Y meteré en el fuego a la tercera parte, y los fundiré como se funde la plata, y los probaré como se prueba el oro. El invocará mi nombre, y yo le oiré, y diré: Pueblo mío; y él dirá: Jehová es mi Dios."},
            {"Malaquías", "2:5", "Mi pacto con él fue de vida y de paz, las cuales cosas yo le di para que me temiera; y tuvo temor de mí, y delante de mi nombre estuvo humillado."},
            {"Malaquías", "2:7", "Porque los labios del sacerdote han de guardar la sabiduría, y de su boca el pueblo buscará la ley; porque mensajero es de Jehová de los ejércitos."},
            {"Malaquías", "3:17", "Y serán para mí especial tesoro, ha dicho Jehová de los ejércitos, en el día en que yo actúe; y los perdonaré, como el hombre que perdona a su hijo que le sirve."},
            {"Malaquías", "3:18", "Entonces os volveréis, y discerniréis la diferencia entre el justo y el malo, entre el que sirve a Dios y el que no le sirve."}
    };

    public static final  String[][] NT_GOSPELS = {
            {"Mateo", "5:6", "Bienaventurados los que tienen hambre y sed de justicia, porque ellos serán saciados."},
            {"Mateo", "5:16", "Así alumbre vuestra luz delante de los hombres, para que vean vuestras buenas obras, y glorifiquen a vuestro Padre que está en los cielos."},
            {"Mateo", "5:48", "Sed, pues, vosotros perfectos, como vuestro Padre que está en los cielos es perfecto."},
            {"Mateo", "6:8", "Porque todo aquel que pide, recibe; y el que busca, halla; y al que llama, se le abrirá."},
            {"Mateo", "8:13", "Id, pues, y aprended lo que significa: Misericordia quiero, y no sacrificio. Porque no he venido a llamar a justos, sino a pecadores, al arrepentimiento."},
            {"Mateo", "11:29", "Llevad mi yugo sobre vosotros, y aprended de mí, que soy manso y humilde de corazón; y hallaréis descanso para vuestras almas;"},
            {"Mateo", "16:24", "Entonces Jesús dijo a sus discípulos: Si alguno quiere venir en pos de mí, niéguese a sí mismo, y tome su cruz, y sígame."},
            {"Mateo", "25:13", "Velad, pues, porque no sabéis el día ni la hora en que el Hijo del Hombre ha de venir."},
            {"Mateo", "28:19", "Por tanto, id, y haced discípulos a todas las naciones, bautizándolos en el nombre del Padre, y del Hijo, y del Espíritu Santo;"},
            {"Mateo", "28:20", "enseñándoles que guarden todas las cosas que os he mandado; y he aquí yo estoy con vosotros todos los días, hasta el fin del mundo. Amén."},
            {"Marcos", "4:20", "Y éstos son los que fueron sembrados en buena tierra: los que oyen la palabra y la reciben, y dan fruto a treinta, a sesenta, y a ciento por uno."},
            {"Marcos", "8:35", "Porque todo el que quiera salvar su vida, la perderá; y todo el que pierda su vida por causa de mí y del evangelio, la salvará."},
            {"Marcos", "9:50", "Buena es la sal; mas si la sal se hace insípida, ¿con qué la sazonaréis? Tened sal en vosotros mismos; y tened paz los unos con los otros."},
            {"Marcos", "10:15", "De cierto os digo, que el que no reciba el reino de Dios como un niño, no entrará en él."},
            {"Marcos", "10:27", "Entonces Jesús, mirándolos, dijo: Para los hombres es imposible, mas para Dios, no; porque todas las cosas son posibles para Dios."},
            {"Marcos", "10:43", "Pero no será así entre vosotros, sino que el que quiera hacerse grande entre vosotros será vuestro servidor,"},
            {"Marcos", "13:35", "Velad, pues, porque no sabéis cuándo vendrá el señor de la casa; si al anochecer, o a la medianoche, o al canto del gallo, o a la mañana;"},
            {"Marcos", "16:15", "Y les dijo: Id por todo el mundo y predicad el evangelio a toda criatura."},
            {"Marcos", "16:16", "El que creyere y fuere bautizado, será salvo; mas el que no creyere, será condenado."},
            {"Lucas", "4:18", "El Espíritu del Señor está sobre mí, Por cuanto me ha ungido para dar buenas nuevas a los pobres; Me ha enviado a sanar a los quebrantados de corazón; A pregonar libertad a los cautivos, Y vista a los ciegos; A poner en libertad a los oprimidos;"},
            {"Lucas", "6:21", "Bienaventurados los que ahora tenéis hambre, porque seréis saciados. Bienaventurados los que ahora lloráis, porque reiréis."},
            {"Lucas", "6:35", "Amad, pues, a vuestros enemigos, y haced bien, y prestad, no esperando de ello nada; y será vuestro galardón grande, y seréis hijos del Altísimo; porque él es benigno para con los ingratos y malos."},
            {"Lucas", "6:45", "El hombre bueno, del buen tesoro de su corazón saca lo bueno; y el hombre malo, del mal tesoro de su corazón saca lo malo; porque de la abundancia del corazón habla la boca."},
            {"Lucas", "9:23", "Y decía a todos: Si alguno quiere venir en pos de mí, niéguese a sí mismo, tome su cruz cada día, y sígame."},
            {"Lucas", "11:13", "Pues si vosotros, siendo malos, sabéis dar buenas dádivas a vuestros hijos, ¿cuánto más vuestro Padre celestial dará el Espíritu Santo a los que se lo pidan?"},
            {"Lucas", "11:28", "Y él dijo: Antes bienaventurados los que oyen la palabra de Dios, y la guardan."},
            {"Lucas", "11:36", "Así que, si todo tu cuerpo está lleno de luz, no teniendo parte alguna de tinieblas, será todo luminoso, como cuando una lámpara te alumbra con su resplandor."},
            {"Lucas", "11:29", "Vosotros, pues, no os preocupéis por lo que habéis de comer, ni por lo que habéis de beber, ni estéis en ansiosa inquietud."},
            {"Lucas", "11:30", "Porque todas estas cosas buscan las gentes del mundo; pero vuestro Padre sabe que tenéis necesidad de estas cosas."},
            {"Lucas", "18:7", "¿Y acaso Dios no hará justicia a sus escogidos, que claman a él día y noche? ¿Se tardará en responderles?"},
            {"Lucas", "24:49", "He aquí, yo enviaré la promesa de mi Padre sobre vosotros; pero quedaos vosotros en la ciudad de Jerusalén, hasta que seáis investidos de poder desde lo alto."},
            {"Juan", "1:12", "Mas a todos los que le recibieron, a los que creen en su nombre, les dio potestad de ser hechos hijos de Dios;"},
            {"Juan", "3:16", "Porque de tal manera amó Dios al mundo, que ha dado a su Hijo unigénito, para que todo aquel que en él cree, no se pierda, mas tenga vida eterna."},
            {"Juan", "3:21", "Mas el que practica la verdad viene a la luz, para que sea manifiesto que sus obras son hechas en Dios."},
            {"Juan", "4:14", "mas el que bebiere del agua que yo le daré, no tendrá sed jamás; sino que el agua que yo le daré será en él una fuente de agua que salte para vida eterna."},
            {"Juan", "4:24", "Dios es Espíritu; y los que le adoran, en espíritu y en verdad es necesario que adoren."},
            {"Juan", "5:39", "Escudriñad las Escrituras; porque a vosotros os parece que en ellas tenéis la vida eterna; y ellas son las que dan testimonio de mí;"},
            {"Juan", "7:38", "El que cree en mí, como dice la Escritura, de su interior correrán ríos de agua viva."},
            {"Juan", "10:9", "Yo soy la puerta; el que por mí entrare, será salvo; y entrará, y saldrá, y hallará pastos."},
            {"Juan", "13:35", "En esto conocerán todos que sois mis discípulos, si tuviereis amor los unos con los otros."},
            {"Juan", "14:26", "Mas el Consolador, el Espíritu Santo, a quien el Padre enviará en mi nombre, él os enseñará todas las cosas, y os recordará todo lo que yo os he dicho."},
            {"Juan", "14:27", "La paz os dejo, mi paz os doy; yo no os la doy como el mundo la da. No se turbe vuestro corazón, ni tenga miedo."},
            {"Juan", "15:5", "Yo soy la vid, vosotros los pámpanos; el que permanece en mí, y yo en él, éste lleva mucho fruto; porque separados de mí nada podéis hacer."},
            {"Juan", "15:7", "Si permanecéis en mí, y mis palabras permanecen en vosotros, pedid todo lo que queréis, y os será hecho."},
            {"Juan", "17:21", "para que todos sean uno; como tú, oh Padre, en mí, y yo en ti, que también ellos sean uno en nosotros; para que el mundo crea que tú me enviaste."}
    };

    public static final  String[][] NT_HISTORICAL = {
            {"Hechos", "1:8", "pero recibiréis poder, cuando haya venido sobre vosotros el Espíritu Santo, y me seréis testigos en Jerusalén, en toda Judea, en Samaria, y hasta lo último de la tierra."},
            {"Hechos", "2:38", "Pedro les dijo: Arrepentíos, y bautícese cada uno de vosotros en el nombre de Jesucristo para perdón de los pecados; y recibiréis el don del Espíritu Santo."},
            {"Hechos", "2:42", "Y perseveraban en la doctrina de los apóstoles, en la comunión unos con otros, en el partimiento del pan y en las oraciones."},
            {"Hechos", "2:47", "alabando a Dios, y teniendo favor con todo el pueblo. Y el Señor añadía cada día a la iglesia los que habían de ser salvos."},
            {"Hechos", "4:20", "porque no podemos dejar de decir lo que hemos visto y oído."},
            {"Hechos", "5:12", "Y por la mano de los apóstoles se hacían muchas señales y prodigios en el pueblo; y estaban todos unánimes en el pórtico de Salomón."},
            {"Hechos", "6:3", "Buscad, pues, hermanos, de entre vosotros a siete varones de buen testimonio, llenos del Espíritu Santo y de sabiduría, a quienes encarguemos de este trabajo."},
            {"Hechos", "6:4", "Y nosotros persistiremos en la oración y en el ministerio de la palabra."},
            {"Hechos", "10:4", "El, mirándole fijamente, y atemorizado, dijo: ¿Qué es, Señor? Y le dijo: Tus oraciones y tus limosnas han subido para memoria delante de Dios."},
            {"Hechos", "13:3", "Entonces, habiendo ayunado y orado, les impusieron las manos y los despidieron."},
            {"Hechos", "13:52", "Y los discípulos estaban llenos de gozo y del Espíritu Santo."},
            {"Hechos", "16:5", "Así que las iglesias eran confirmadas en la fe, y aumentaban en número cada día."},
            {"Hechos", "18:28", "porque con gran vehemencia refutaba públicamente a los judíos, demostrando por las Escrituras que Jesús era el Cristo."},
            {"Hechos", "22:15", "Porque serás testigo suyo a todos los hombres, de lo que has visto y oído."}
    };

    public static final  String[][] NT_PAULINE = {
            {"Romanos", "1:16", "Porque no me avergüenzo del evangelio, porque es poder de Dios para salvación a todo aquel que cree; al judío primeramente, y también al griego."},
            {"Romanos", "5:1", "Justificados, pues, por la fe, tenemos paz para con Dios por medio de nuestro Señor Jesucristo;"},
            {"Romanos", "6:22", "Mas ahora que habéis sido libertados del pecado y hechos siervos de Dios, tenéis por vuestro fruto la santificación, y como fin, la vida eterna."},
            {"Romanos", "8:1", "Ahora, pues, ninguna condenación hay para los que están en Cristo Jesús, los que no andan conforme a la carne, sino conforme al Espíritu."},
            {"Romanos", "8:14", "Porque todos los que son guiados por el Espíritu de Dios, éstos son hijos de Dios."},
            {"Romanos", "10:9", "que si confesares con tu boca que Jesús es el Señor, y creyeres en tu corazón que Dios le levantó de los muertos, serás salvo."},
            {"Romanos", "12:2", "No os conforméis a este siglo, sino transformaos por medio de la renovación de vuestro entendimiento, para que comprobéis cuál sea la buena voluntad de Dios, agradable y perfecta."},
            {"Romanos", "12:5", "así nosotros, siendo muchos, somos un cuerpo en Cristo, y todos miembros los unos de los otros."},
            {"1 Corintios", "1:10", "Os ruego, pues, hermanos, por el nombre de nuestro Señor Jesucristo, que habléis todos una misma cosa, y que no haya entre vosotros divisiones, sino que estéis perfectamente unidos en una misma mente y en un mismo parecer."},
            {"1 Corintios", "1:18", "Porque la palabra de la cruz es locura a los que se pierden; pero a los que se salvan, esto es, a nosotros, es poder de Dios."},
            {"1 Corintios", "2:11", "Porque nadie puede poner otro fundamento que el que está puesto, el cual es Jesucristo."},
            {"1 Corintios", "6:12", "Todas las cosas me son lícitas, mas no todas convienen; todas las cosas me son lícitas, mas yo no me dejaré dominar de ninguna."},
            {"1 Corintios", "10:13", "No os ha sobrevenido ninguna tentación que no sea humana; pero fiel es Dios, que no os dejará ser tentados más de lo que podéis resistir, sino que dará también juntamente con la tentación la salida, para que podáis soportar."},
            {"1 Corintios", "10:33", "como también yo en todas las cosas agrado a todos, no procurando mi propio beneficio, sino el de muchos, para que sean salvos."},
            {"1 Corintios", "14:40", "pero hágase todo decentemente y con orden."},
            {"1 Corintios", "16:14", "Todas vuestras cosas sean hechas con amor."},
            {"2 Corintios", "3:5", "no que seamos competentes por nosotros mismos para pensar algo como de nosotros mismos, sino que nuestra competencia proviene de Dios,"},
            {"2 Corintios", "3:17", "Porque el Señor es el Espíritu; y donde está el Espíritu del Señor, allí hay libertad."},
            {"2 Corintios", "4:5", "Porque no nos predicamos a nosotros mismos, sino a Jesucristo como Señor, y a nosotros como vuestros siervos por amor de Jesús."},
            {"2 Corintios", "4:18", "no mirando nosotros las cosas que se ven, sino las que no se ven; pues las cosas que se ven son temporales, pero las que no se ven son eternas."},
            {"2 Corintios", "7:1", "Así que, amados, puesto que tenemos tales promesas, limpiémonos de toda contaminación de carne y de espíritu, perfeccionando la santidad en el temor de Dios."},
            {"2 Corintios", "9:6", "Pero esto digo: El que siembra escasamente, también segará escasamente; y el que siembra generosamente, generosamente también segará."},
            {"2 Corintios", "10:18", "porque no es aprobado el que se alaba a sí mismo, sino aquel a quien Dios alaba."},
            {"2 Corintios", "12:9", "Y me ha dicho: Bástate mi gracia; porque mi poder se perfecciona en la debilidad. Por tanto, de buena gana me gloriaré más bien en mis debilidades, para que repose sobre mí el poder de Cristo."},
            {"Gálatas", "1:10", "Pues, ¿busco ahora el favor de los hombres, o el de Dios? ¿O trato de agradar a los hombres? Pues si todavía agradara a los hombres, no sería siervo de Cristo."},
            {"Gálatas", "2:20", "Con Cristo estoy juntamente crucificado, y ya no vivo yo, mas vive Cristo en mí; y lo que ahora vivo en la carne, lo vivo en la fe del Hijo de Dios, el cual me amó y se entregó a sí mismo por mí."},
            {"Gálatas", "3:28", "Ya no hay judío ni griego; no hay esclavo ni libre; no hay varón ni mujer; porque todos vosotros sois uno en Cristo Jesús."},
            {"Gálatas", "5:17", "Porque el deseo de la carne es contra el Espíritu, y el del Espíritu es contra la carne; y éstos se oponen entre sí, para que no hagáis lo que quisiereis."},
            {"Gálatas", "6:2", "Sobrellevad los unos las cargas de los otros, y cumplid así la ley de Cristo."},
            {"Gálatas", "6:9", "No nos cansemos, pues, de hacer bien; porque a su tiempo segaremos, si no desmayamos."},
            {"Efesios", "2:8", "Porque por gracia sois salvos por medio de la fe; y esto no de vosotros, pues es don de Dios;"},
            {"Efesios", "4:13", "hasta que todos lleguemos a la unidad de la fe y del conocimiento del Hijo de Dios, a un varón perfecto, a la medida de la estatura de la plenitud de Cristo;"},
            {"Efesios", "4:23", "y renovaos en el espíritu de vuestra mente,"},
            {"Efesios", "4:30", "Y no contristéis al Espíritu Santo de Dios, con el cual fuisteis sellados para el día de la redención."},
            {"Efesios", "5:16", "aprovechando bien el tiempo, porque los días son malos."},
            {"Efesios", "6:18", "orando en todo tiempo con toda oración y súplica en el Espíritu, y velando en ello con toda perseverancia y súplica por todos los santos;"},
            {"Filipenses", "2:13", "porque Dios es el que en vosotros produce así el querer como el hacer, por su buena voluntad."},
            {"Filipenses", "3:8", "Y ciertamente, aun estimo todas las cosas como pérdida por la excelencia del conocimiento de Cristo Jesús, mi Señor, por amor del cual lo he perdido todo, y lo tengo por basura, para ganar a Cristo,"},
            {"Filipenses", "3:14", "prosigo a la meta, al premio del supremo llamamiento de Dios en Cristo Jesús."},
            {"Filipenses", "4:6", "Por nada estéis afanosos, sino sean conocidas vuestras peticiones delante de Dios en toda oración y ruego, con acción de gracias."},
            {"Colosenses", "2:8", "Mirad que nadie os engañe por medio de filosofías y huecas sutilezas, según las tradiciones de los hombres, conforme a los rudimentos del mundo, y no según Cristo."},
            {"Colosenses", "3:1", "Si, pues, habéis resucitado con Cristo, buscad las cosas de arriba, donde está Cristo sentado a la diestra de Dios."},
            {"Colosenses", "3:2", "Poned la mira en las cosas de arriba, no en las de la tierra."},
            {"Colosenses", "3:23", "Y todo lo que hagáis, hacedlo de corazón, como para el Señor y no para los hombres;"},
            {"Colosenses", "3:24", "sabiendo que del Señor recibiréis la recompensa de la herencia, porque a Cristo el Señor servís."},
            {"Colosenses", "4:2", "Perseverad en la oración, velando en ella con acción de gracias;"},
            {"1 Tesalonicenses", "3:7", "Pues no nos ha llamado Dios a inmundicia, sino a santificación."},
            {"1 Tesalonicenses", "5:8", "Pero nosotros, que somos del día, seamos sobrios, habiéndonos vestido con la coraza de fe y de amor, y con la esperanza de salvación como yelmo."},
            {"1 Tesalonicenses", "5:16", "Estad siempre gozosos."},
            {"1 Tesalonicenses", "5:17", "Orad sin cesar."},
            {"1 Tesalonicenses", "5:18", "Dad gracias en todo, porque esta es la voluntad de Dios para con vosotros en Cristo Jesús."},
            {"1 Tesalonicenses", "5:19", "No apaguéis al Espíritu."},
            {"2 Tesalonicenses", "2:15", "Así que, hermanos, estad firmes, y retened la doctrina que habéis aprendido, sea por palabra, o por carta nuestra."},
            {"2 Tesalonicenses", "3:1", "Por lo demás, hermanos, orad por nosotros, para que la palabra del Señor corra y sea glorificada, así como lo fue entre vosotros,"},
            {"2 Tesalonicenses", "3:3", "Pero fiel es el Señor, que os afirmará y guardará del mal."},
            {"1 Timoteo", "1:15", "Palabra fiel y digna de ser recibida por todos: que Cristo Jesús vino al mundo para salvar a los pecadores, de los cuales yo soy el primero."},
            {"1 Timoteo", "2:1", "Exhorto ante todo, a que se hagan rogativas, oraciones, peticiones y acciones de gracias, por todos los hombres;"},
            {"1 Timoteo", "2:5", "Porque hay un solo Dios, y un solo mediador entre Dios y los hombres, Jesucristo hombre,"},
            {"1 Timoteo", "4:16", "Ten cuidado de ti mismo y de la doctrina; persiste en ello, pues haciendo esto, te salvarás a ti mismo y a los que te oyeren."},
            {"1 Timoteo", "6:8", "Así que, teniendo sustento y abrigo, estemos contentos con esto."},
            {"1 Timoteo", "6:12", "Pelea la buena batalla de la fe, echa mano de la vida eterna, a la cual asimismo fuiste llamado, habiendo hecho la buena profesión delante de muchos testigos."},
            {"2 Timoteo", "1:7", "Porque no nos ha dado Dios espíritu de cobardía, sino de poder, de amor y de dominio propio."},
            {"2 Timoteo", "2:4", "Ninguno que milita se enreda en los negocios de la vida, a fin de agradar a aquel que lo tomó por soldado."},
            {"2 Timoteo", "2:15", "Procura con diligencia presentarte a Dios aprobado, como obrero que no tiene de qué avergonzarse, que usa bien la palabra de verdad."},
            {"2 Timoteo", "2:22", "Huye también de las pasiones juveniles, y sigue la justicia, la fe, el amor y la paz, con los que de corazón limpio invocan al Señor."},
            {"2 Timoteo", "2:24", "Porque el siervo del Señor no debe ser contencioso, sino amable para con todos, apto para enseñar, sufrido;"},
            {"2 Timoteo", "4:5", "Pero tú sé sobrio en todo, soporta las aflicciones, haz obra de evangelista, cumple tu ministerio."},
            {"Tito", "2:1", "Pero tú habla lo que está de acuerdo con la sana doctrina."},
            {"Tito", "2:7", "presentándote tú en todo como ejemplo de buenas obras; en la enseñanza mostrando integridad, seriedad,"}
    };

    public static final  String[][] NT_GENERAL = {
            {"Hebreos", "2:1", "Por tanto, es necesario que con más diligencia atendamos a las cosas que hemos oído, no sea que nos deslicemos."},
            {"Hebreos", "2:18", "Pues en cuanto él mismo padeció siendo tentado, es poderoso para socorrer a los que son tentados."},
            {"Hebreos", "3:12", "Mirad, hermanos, que no haya en ninguno de vosotros corazón malo de incredulidad para apartarse del Dios vivo;"},
            {"Hebreos", "4:13", "Y no hay cosa creada que no sea manifiesta en su presencia; antes bien todas las cosas están desnudas y abiertas a los ojos de aquel a quien tenemos que dar cuenta."},
            {"Hebreos", "4:16", "Acerquémonos, pues, confiadamente al trono de la gracia, para alcanzar misericordia y hallar gracia para el oportuno socorro."},
            {"Hebreos", "6:10", "Porque Dios no es injusto para olvidar vuestra obra y el trabajo de amor que habéis mostrado hacia su nombre, habiendo servido a los santos y sirviéndoles aún."},
            {"Hebreos", "9:24", "Porque no entró Cristo en el santuario hecho de mano, figura del verdadero, sino en el cielo mismo para presentarse ahora por nosotros ante Dios;"},
            {"Hebreos", "9:28", "así también Cristo fue ofrecido una sola vez para llevar los pecados de muchos; y aparecerá por segunda vez, sin relación con el pecado, para salvar a los que le esperan."},
            {"Hebreos", "10:22", "acerquémonos con corazón sincero, en plena certidumbre de fe, purificados los corazones de mala conciencia, y lavados los cuerpos con agua pura"},
            {"Hebreos", "10:25", "no dejando de congregarnos, como algunos tienen por costumbre, sino exhortándonos; y tanto más, cuanto veis que aquel día se acerca."},
            {"Hebreos", "10:39", "Pero nosotros no somos de los que retroceden para perdición, sino de los que tienen fe para preservación del alma."},
            {"Hebreos", "11:6", "Pero sin fe es imposible agradar a Dios; porque es necesario que el que se acerca a Dios crea que le hay, y que es galardonador de los que le buscan."},
            {"Hebreos", "12:1", "Por tanto, nosotros también, teniendo en derredor nuestro tan grande nube de testigos, despojémonos de todo peso y del pecado que nos asedia, y corramos con paciencia la carrera que tenemos por delante,"},
            {"Hebreos", "12:15", "Mirad bien, no sea que alguno deje de alcanzar la gracia de Dios; que brotando alguna raíz de amargura, os estorbe, y por ella muchos sean contaminados;"},
            {"Hebreos", "13:15", "Así que, ofrezcamos siempre a Dios, por medio de él, sacrificio de alabanza, es decir, fruto de labios que confiesan su nombre."},
            {"Santiago", "1:5", "Y si alguno de vosotros tiene falta de sabiduría, pídala a Dios, el cual da a todos abundantemente y sin reproche, y le será dada."},
            {"Santiago", "1:6", "Pero pida con fe, no dudando nada; porque el que duda es semejante a la onda del mar, que es arrastrada por el viento y echada de una parte a otra."},
            {"Santiago", "1:12", "Bienaventurado el varón que soporta la tentación; porque cuando haya resistido la prueba, recibirá la corona de vida, que Dios ha prometido a los que le aman."},
            {"Santiago", "1:19", "Por esto, mis amados hermanos, todo hombre sea pronto para oír, tardo para hablar, tardo para airarse;"},
            {"Santiago", "2:26", "Porque como el cuerpo sin espíritu está muerto, así también la fe sin obras está muerta."},
            {"Santiago", "3:11", "¿Acaso alguna fuente echa por una misma abertura agua dulce y amarga?"},
            {"Santiago", "3:17", "Pero la sabiduría que es de lo alto es primeramente pura, después pacífica, amable, benigna, llena de misericordia y de buenos frutos, sin incertidumbre ni hipocresía."},
            {"Santiago", "4:3", "Pedís, y no recibís, porque pedís mal, para gastar en vuestros deleites."},
            {"Santiago", "4:4", "!!Oh almas adúlteras! ¿No sabéis que la amistad del mundo es enemistad contra Dios? Cualquiera, pues, que quiera ser amigo del mundo, se constituye enemigo de Dios."},
            {"Santiago", "4:7", "Someteos, pues, a Dios; resistid al diablo, y huirá de vosotros."},
            {"Santiago", "5:8", "Tened también vosotros paciencia, y afirmad vuestros corazones; porque la venida del Señor se acerca."},
            {"1 Pedro", "1:15", "sino, como aquel que os llamó es santo, sed también vosotros santos en toda vuestra manera de vivir;"},
            {"1 Pedro", "2:2", "desead, como niños recién nacidos, la leche espiritual no adulterada, para que por ella crezcáis para salvación,"},
            {"1 Pedro", "2:9", "Mas vosotros sois linaje escogido, real sacerdocio, nación santa, pueblo adquirido por Dios, para que anunciéis las virtudes de aquel que os llamó de las tinieblas a su luz admirable;"},
            {"1 Pedro", "2:15", "Porque esta es la voluntad de Dios: que haciendo bien, hagáis callar la ignorancia de los hombres insensatos;"},
            {"1 Pedro", "3:8", "Finalmente, sed todos de un mismo sentir, compasivos, amándoos fraternalmente, misericordiosos, amigables;"},
            {"1 Pedro", "3:12", "Porque los ojos del Señor están sobre los justos, Y sus oídos atentos a sus oraciones; Pero el rostro del Señor está contra aquellos que hacen el mal."},
            {"1 Pedro", "4:8", "Y ante todo, tened entre vosotros ferviente amor; porque el amor cubrirá multitud de pecados."},
            {"1 Pedro", "5:6", "Humillaos, pues, bajo la poderosa mano de Dios, para que él os exalte cuando fuere tiempo;"},
            {"1 Pedro", "5:7", "echando toda vuestra ansiedad sobre él, porque él tiene cuidado de vosotros."},
            {"2 Pedro", "1:21", "porque nunca la profecía fue traída por voluntad humana, sino que los santos hombres de Dios hablaron siendo inspirados por el Espíritu Santo."},
            {"2 Pedro", "3:14", "Por lo cual, oh amados, estando en espera de estas cosas, procurad con diligencia ser hallados por él sin mancha e irreprensibles, en paz."},
            {"2 Pedro", "3:18", "Antes bien, creced en la gracia y el conocimiento de nuestro Señor y Salvador Jesucristo. A él sea gloria ahora y hasta el día de la eternidad. Amén."},
            {"1 Juan", "1:9", "Si confesamos nuestros pecados, él es fiel y justo para perdonar nuestros pecados, y limpiarnos de toda maldad."},
            {"1 Juan", "2:1", "Hijitos míos, estas cosas os escribo para que no pequéis; y si alguno hubiere pecado, abogado tenemos para con el Padre, a Jesucristo el justo."},
            {"1 Juan", "2:22", "y cualquiera cosa que pidiéremos la recibiremos de él, porque guardamos sus mandamientos, y hacemos las cosas que son agradables delante de él."},
            {"1 Juan", "4:1", "Amados, no creáis a todo espíritu, sino probad los espíritus si son de Dios; porque muchos falsos profetas han salido por el mundo."},
            {"1 Juan", "4:18", "En el amor no hay temor, sino que el perfecto amor echa fuera el temor; porque el temor lleva en sí castigo. De donde el que teme, no ha sido perfeccionado en el amor."},
            {"2 Juan", "1:9", "Cualquiera que se extravía, y no persevera en la doctrina de Cristo, no tiene a Dios; el que persevera en la doctrina de Cristo, ése sí tiene al Padre y al Hijo."},
            {"2 Juan", "1:10", "Si alguno viene a vosotros, y no trae esta doctrina, no lo recibáis en casa, ni le digáis: !!Bienvenido!"},
            {"Judas", "1:20", "Pero vosotros, amados, edificándoos sobre vuestra santísima fe, orando en el Espíritu Santo,"},
            {"Judas", "1:21", "conservaos en el amor de Dios, esperando la misericordia de nuestro Señor Jesucristo para vida eterna."}
    };

    public static final  String[][] NT_PROPHECY = {
            {"Apocalipsis", "2:5", "Recuerda, por tanto, de dónde has caído, y arrepiéntete, y haz las primeras obras; pues si no, vendré pronto a ti, y quitaré tu candelero de su lugar, si no te hubieres arrepentido."},
            {"Apocalipsis", "2:19", "Yo conozco tus obras, y amor, y fe, y servicio, y tu paciencia, y que tus obras postreras son más que las primeras."},
            {"Apocalipsis", "3:3", "Acuérdate, pues, de lo que has recibido y oído; y guárdalo, y arrepiéntete. Pues si no velas, vendré sobre ti como ladrón, y no sabrás a qué hora vendré sobre ti."},
            {"Apocalipsis", "3:8", "Yo conozco tus obras; he aquí, he puesto delante de ti una puerta abierta, la cual nadie puede cerrar; porque aunque tienes poca fuerza, has guardado mi palabra, y no has negado mi nombre."},
            {"Apocalipsis", "3:19", "Yo reprendo y castigo a todos los que amo; sé, pues, celoso, y arrepiéntete."},
            {"Apocalipsis", "3:20", "He aquí, yo estoy a la puerta y llamo; si alguno oye mi voz y abre la puerta, entraré a él, y cenaré con él, y él conmigo. "},
            {"Apocalipsis", "16:15", "He aquí, yo vengo como ladrón. Bienaventurado el que vela, y guarda sus ropas, para que no ande desnudo, y vean su vergüenza."},
            {"Apocalipsis", "22:12", "He aquí yo vengo pronto, y mi galardón conmigo, para recompensar a cada uno según sea su obra."}
    };
}
